### ISSUE TITLE
CMS Content > Feature Panels

### ISSUE THREAD

**Issue by danlechambre** [grief-matters/grief-matters-cms#115]
**Description**
We need to determine the final set of Feature Panels for the Home Page content type

**Task List**

- [ ] Document the Feature Panel creation process so that not dependent on DC
- [ ] Check current Feature Panels have the correct content
- [ ] Add Remaining Feature Panels
  - [ ] Featured Topics (should we list them all? Or only some to maintain impact?)
  - [ ] Spotlight
  - [ ] Book Nook
  - [ ] Underserved Populations ??
