### ISSUE TITLE
CMS Content > About Page

### ISSUE THREAD

**Issue by danlechambre** [grief-matters/grief-matters-cms#116]
**Description**
We need to complete the content required for the About Page in the CMS in order to build the About Us page on the website

**Task List**
- [ ] 'People' content type needs to be populated with photos, bios, and roles
- [ ] 'Our Story' needs to be written
- [ ] 'Team Intro' needs to be written

**Comment by danlechambre** [comment]
Track content and CMS dev requirements separately once backlog grooming is finished
