### ISSUE TITLE
CMS Content > Add 'Explore Categories' Feature Panel 

### ISSUE THREAD

**Issue by danlechambre** [grief-matters/grief-matters-cms#125]
### Description

**Requirements**

- There should be a new Feature Panel on the Home Page that appears first in the panel list.
- It should be called: "Explore Topics We Cover" _(TBC by Camille)_ 
- It should display this specific list of categories:
  - Understanding Grief
  - For the Newly Bereaved
  - Peer Support & Support Groups
  - Resilience
  - Self-Care
  - Therapy
  - COVID-19
  - Preparing for Death
  - Supporting Someone Else
- The footer link should be labelled something like... "explore all topics..." and take users to our main topic exploration page

_is the order above correct?_

**Considerations and Clarifications**

- It was mentioned that it should include Underserved Groups - I don't think this is right as these groups are not topics. We can create a small feature panel that appears just after
- Supporting Someone Else already has its own main navigation item and Feature Panel - should it be included here?
- Mention of getting rid of COVID-19 as its no longer a category - but we did a lot of work to add COVID as its own category with its own specialist sub-categories - so confused on direction of this one and/or why we'd want to remove it?
- Do we just want a "Row of Three" non category related photos across the top - or do we want to show the first 3 items to be like the tiles in the original design?
- Do we want a leading description for this panel like the others? e.g. "We cover a wide range of topics...etc..."
- Can we extend the existing "Resource Page Link" content type schema to cover these 'fancy' links?

### Tasks

- [ ] Ensure existing content schemas cover use case
- [ ] Ensure we can link to the 'explorer topics' page
- [ ] The listed categories will need descriptions adding within the CMS - the field is already there - Camille should have the copy that needs to be entered
- [ ] Create the new Feature Panel document
