### ISSUE TITLE
CMS Content > "Featured Topics" Feature Panel

### ISSUE THREAD

**Issue by danlechambre** [grief-matters/grief-matters-cms#127]
### Description

We need a "Featured Topics" feature panel on the Home Page to highlight topics of specific interest that may otherwise be hard to find, including them on the Home Page means they are easy to find for users that need them

**Requirements**

- Title should be 'Featured Topics'
- Description: "An in-depth look at issues that often go unaddressed"
- First item should be a "Row of Three" photos
- List of "Resource Page Links" showing the Featured Topics

**Considerations**

- Should the panel list all 'featured topics'? Otherwise we'd need a specific "Featured Topics" page?
- We may need to review how we define Featured Topics in the CMS so it can easily be repurposed in the main navigation and explore topics pages
- We may need another featured content content type to hand "category children" - "Auto Links From Category"? or something similar
- Should we include a footer link? 'explorer all topics' perhaps?

### Tasks

- [x] Complete any required CMS schema work
- [x] grief-matters/whygriefmatters.org#57
- [x] Create the Feature Panel as per the requirements above
