### ISSUE TITLE
CMS > Production Github Setup

### ISSUE THREAD

**Issue by danlechambre** [grief-matters/grief-matters-cms#72]
**Problem Statement**
With multiple devs on project and data in production - we want to avoid any untested/non-reviewed changes going to main branch 

**Tasks**

- [ ] Branch protection rules
- [ ] Git workflow - copy production dataset to dev on PR completion
- [ ] Git workflow - build using Github rather than Netlify (cheaper)
- [ ] Dataset backup

**Comment by danlechambre** [comment]
Mostly done - will log new issues as things arise
